/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atividadepratica.view;

import javax.swing.JFileChooser;

/**
 *
 * @author abreu
 */
public class Cadastro_Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_Clientes
     */
    public Cadastro_Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        ButtonAbrir = new javax.swing.JButton();
        ButtonSalvar = new javax.swing.JButton();
        campoTextoAbrir = new javax.swing.JTextField();
        campoTextoSalvar = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        campoTextoCPFCliente = new javax.swing.JTextField();
        label_Email = new javax.swing.JLabel();
        campoTextoEmailCliente = new javax.swing.JTextField();
        label_CPF = new javax.swing.JLabel();
        label_Telefone = new javax.swing.JLabel();
        campoTextoTelefoneCliente = new javax.swing.JTextField();
        campoTextoNomeCliente = new javax.swing.JTextField();
        label_Nome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setText("CADASTRO CLIENTES");

        ButtonAbrir.setText("ABRIR");
        ButtonAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonAbrirMouseClicked(evt);
            }
        });

        ButtonSalvar.setText("SALVAR");
        ButtonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonSalvarMouseClicked(evt);
            }
        });

        campoTextoAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoAbrirActionPerformed(evt);
            }
        });

        campoTextoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoSalvarActionPerformed(evt);
            }
        });

        campoTextoCPFCliente.setText("CPF");
        campoTextoCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoCPFClienteActionPerformed(evt);
            }
        });

        label_Email.setText("Email....:");

        campoTextoEmailCliente.setText("Email");

        label_CPF.setText("CPF.........:");

        label_Telefone.setText("Telefone:");

        campoTextoTelefoneCliente.setText("Telefone");
        campoTextoTelefoneCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoTelefoneClienteActionPerformed(evt);
            }
        });

        campoTextoNomeCliente.setText("Nome");
        campoTextoNomeCliente.setActionCommand("<Not Set>");
        campoTextoNomeCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campoTextoNomeCliente.setName(""); // NOI18N

        label_Nome.setText("Nome.....:");

        jLayeredPane1.setLayer(campoTextoCPFCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(label_Email, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(campoTextoEmailCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(label_CPF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(label_Telefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(campoTextoTelefoneCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(campoTextoNomeCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(label_Nome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(label_Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoTextoNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(label_Email)
                        .addGap(18, 18, 18)
                        .addComponent(campoTextoEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(label_CPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoTextoCPFCliente))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(label_Telefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoTextoTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Nome)
                    .addComponent(campoTextoNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_CPF)
                    .addComponent(campoTextoCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Telefone)
                    .addComponent(campoTextoTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Email)
                    .addComponent(campoTextoEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(titulo)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ButtonAbrir)
                                .addComponent(ButtonSalvar))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoTextoAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoTextoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAbrir)
                    .addComponent(campoTextoAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSalvar)
                    .addComponent(campoTextoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoTextoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoAbrirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoAbrirActionPerformed

    private void campoTextoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoSalvarActionPerformed

    private void ButtonAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAbrirMouseClicked
        // TODO add your handling code here:
        JFileChooser seletor = new JFileChooser();
        int retorno = seletor.showOpenDialog(this);
        
        if (retorno == JFileChooser.APPROVE_OPTION) {
            campoTextoAbrir.setText(seletor.getSelectedFile().getAbsolutePath());
        } else {
            //Arquivo não encontrado
            campoTextoAbrir.setText("");
        }
    }//GEN-LAST:event_ButtonAbrirMouseClicked

    private void ButtonSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSalvarMouseClicked
        // TODO add your handling code here:
        JFileChooser seletor = new JFileChooser();
        int retorno = seletor.showSaveDialog(this);
        
        if (retorno == JFileChooser.APPROVE_OPTION) {
            campoTextoSalvar.setText(seletor.getSelectedFile().getAbsolutePath());
        } else {
            //Arquivo não encontrado
            campoTextoSalvar.setText("");
        }
    }//GEN-LAST:event_ButtonSalvarMouseClicked

    private void campoTextoCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoCPFClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoCPFClienteActionPerformed

    private void campoTextoTelefoneClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoTelefoneClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoTelefoneClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAbrir;
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JTextField campoTextoAbrir;
    private javax.swing.JTextField campoTextoCPFCliente;
    private javax.swing.JTextField campoTextoEmailCliente;
    private javax.swing.JTextField campoTextoNomeCliente;
    private javax.swing.JTextField campoTextoSalvar;
    private javax.swing.JTextField campoTextoTelefoneCliente;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel label_CPF;
    private javax.swing.JLabel label_Email;
    private javax.swing.JLabel label_Nome;
    private javax.swing.JLabel label_Telefone;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
