/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atividadepratica.view;

import javax.swing.JFileChooser;
import atividadepratica.controller.ControllerClientesArqTxt;
/**
 *
 * @author abreu
 */
public class Cadastro_Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_Clientes
     */
    public Cadastro_Clientes() {
        initComponents();
    }
    
    ControllerClientesArqTxt controle = new ControllerClientesArqTxt();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        titulo = new javax.swing.JLabel();
        label_Nome = new javax.swing.JLabel();
        campoTextoCPFCliente = new javax.swing.JTextField();
        campoTextoEmailCliente = new javax.swing.JTextField();
        campoTextoTelefoneCliente = new javax.swing.JTextField();
        campoTextoNomeCliente = new javax.swing.JTextField();
        label_Email = new javax.swing.JLabel();
        label_CPF = new javax.swing.JLabel();
        label_Telefone = new javax.swing.JLabel();
        labelLocalArquivo = new javax.swing.JLabel();
        buttonAbrir = new javax.swing.JButton();
        buttonSalvar = new javax.swing.JButton();
        buttonFechar = new javax.swing.JButton();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setText("CADASTRO CLIENTES");

        label_Nome.setText("Nome.....:");

        campoTextoCPFCliente.setText("CPF");
        campoTextoCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoCPFClienteActionPerformed(evt);
            }
        });

        campoTextoEmailCliente.setText("Email");
        campoTextoEmailCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoEmailClienteActionPerformed(evt);
            }
        });

        campoTextoTelefoneCliente.setText("Telefone");
        campoTextoTelefoneCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoTelefoneClienteActionPerformed(evt);
            }
        });

        campoTextoNomeCliente.setText("Nome");
        campoTextoNomeCliente.setActionCommand("<Not Set>");
        campoTextoNomeCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campoTextoNomeCliente.setName(""); // NOI18N

        label_Email.setText("Email....:");

        label_CPF.setText("CPF.........:");

        label_Telefone.setText("Telefone:");

        labelLocalArquivo.setText("Salvo em: ...");

        buttonAbrir.setText("Abrir");
        buttonAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAbrirMouseClicked(evt);
            }
        });

        buttonSalvar.setText("Salvar");
        buttonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSalvarMouseClicked(evt);
            }
        });
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        buttonFechar.setText("Fechar");
        buttonFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonFecharMouseClicked(evt);
            }
        });
        buttonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLocalArquivo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonAbrir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonFechar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label_Telefone)
                                            .addComponent(label_Email))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoTextoEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoTextoTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Nome)
                            .addComponent(label_CPF))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTextoCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {campoTextoCPFCliente, campoTextoEmailCliente, campoTextoNomeCliente, campoTextoTelefoneCliente});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_Nome)
                            .addComponent(campoTextoNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_CPF)
                            .addComponent(campoTextoCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_Telefone)
                            .addComponent(campoTextoTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_Email)
                            .addComponent(campoTextoEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAbrir)
                    .addComponent(buttonSalvar)
                    .addComponent(buttonFechar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(labelLocalArquivo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {campoTextoCPFCliente, campoTextoEmailCliente, campoTextoNomeCliente, campoTextoTelefoneCliente});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoTextoCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoCPFClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoCPFClienteActionPerformed

    private void campoTextoTelefoneClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoTelefoneClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoTelefoneClienteActionPerformed

    private void campoTextoEmailClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoEmailClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoEmailClienteActionPerformed

    private void buttonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonFecharActionPerformed

    private void buttonFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFecharMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonFecharMouseClicked

    private void buttonAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAbrirMouseClicked
        // TODO add your handling code here:
        JFileChooser seletor = new JFileChooser();
        int retorno = seletor.showOpenDialog(this);
        
        if (retorno == JFileChooser.APPROVE_OPTION) {
            labelLocalArquivo.setText(seletor.getSelectedFile().getAbsolutePath());
            controle.setArq(seletor.getSelectedFile());
            if (controle.ler()) {
                System.out.println("Arquivo lido");
            } else {
                System.out.println("Arquivo não lido");
            }
            controle.scanCliente();
            /*
            String aux = controle.getTexto();
            System.out.println("String: " + aux);
            this.painelTextoConteúdo.setText(aux);
            */
            this.campoTextoNomeCliente.setText(controle.getCliente().getNomeCliente());
            this.campoTextoCPFCliente.setText(controle.getCliente().getCpfCliente());
            this.campoTextoTelefoneCliente.setText(controle.getCliente().getTelefoneCliente());
            this.campoTextoEmailCliente.setText(controle.getCliente().getEmailCliente());
            
            controle.getCliente().mostraDados();
            
        } else {
            //Arquivo não encontrado
            labelLocalArquivo.setText("");
        }
    }//GEN-LAST:event_buttonAbrirMouseClicked

    private void buttonSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSalvarMouseClicked
        // TODO add your handling code here:
        JFileChooser seletor = new JFileChooser();
        int retorno = seletor.showSaveDialog(this);
        
        if (retorno == JFileChooser.APPROVE_OPTION) {
            labelLocalArquivo.setText(seletor.getSelectedFile().getAbsolutePath());
            controle.setArq(seletor.getSelectedFile());
            controle.setCliente(this.campoTextoNomeCliente.getText(),this.campoTextoCPFCliente.getText(),this.campoTextoTelefoneCliente.getText(),this.campoTextoEmailCliente.getText());
            System.out.println("Cliente criado!"); 
            controle.getCliente().mostraDados();
            controle.registrarCliente();
            
        } else {
            //Arquivo não encontrado
            labelLocalArquivo.setText("");
        }
    }//GEN-LAST:event_buttonSalvarMouseClicked

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAbrir;
    private javax.swing.JButton buttonFechar;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JTextField campoTextoCPFCliente;
    private javax.swing.JTextField campoTextoEmailCliente;
    private javax.swing.JTextField campoTextoNomeCliente;
    private javax.swing.JTextField campoTextoTelefoneCliente;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel labelLocalArquivo;
    private javax.swing.JLabel label_CPF;
    private javax.swing.JLabel label_Email;
    private javax.swing.JLabel label_Nome;
    private javax.swing.JLabel label_Telefone;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
